#!/bin/bash
# Lapita dead-code cleanup — HIGH CONFIDENCE ONLY
# Generated by dead-code audit. Review before running.
# Run from the PROJECT ROOT (the folder containing src/, app/, package.json).
set -euo pipefail

if [[ ! -d "src" || ! -d "app" ]]; then
  echo "ERROR: 'src/' and 'app/' not found in the current directory."
  echo "Run this script from your project root, e.g.:"
  echo "  cd /path/to/lapita && ./cleanup-high-confidence.sh"
  exit 1
fi

remove() {
  local path="$1"
  local desc="$2"
  if [[ -e "$path" ]]; then
    rm -rf "$path"
    echo "Deleted: $path  ($desc)"
  else
    echo "Skipped (already gone): $path"
  fi
}

# 1. Orphaned "order tracking" summary component — exports OrderSummary,
#    never imported anywhere (app/orders/lookup/page.tsx builds its own
#    inline order display instead).
remove "src/components/checkout/order-summary.tsx" "unused component"

# 2. Orphaned "order tracking" summary component — exports PaymentSummary,
#    never imported anywhere.
remove "src/components/checkout/payment-summary.tsx" "unused component"

# 3. Orphaned "order tracking" summary component — exports
#    ShippingAddressSummary, never imported anywhere.
remove "src/components/checkout/shipping-address-summary.tsx" "unused component"

# 4. Homepage newsletter CTA section — exports NewsletterCta, never
#    imported into app/page.tsx or anywhere else.
remove "src/components/home/newsletter-cta.tsx" "unused component"

# 5. Empty hooks directory (matches components.json's @/hooks alias but
#    contains zero files — the one hook that exists, useGalleryStage,
#    lives colocated under src/components/shop/product-gallery/ instead).
remove "src/hooks" "empty directory"
remove "app/api/track" "unauthenticated example endpoint, unused"
remove "src/components/TrackShipment.jsx" "unused example component"

echo "Done."

